	SUBROUTINE ELECTRON_DENSITY_CALC_V2(ED_TOT,ND)
!
	USE MOD_CMFGEN
	IMPLICIT NONE
!
	INTEGER :: ND
	REAL*8 :: ED_TOT(ND)
!
	INTEGER :: ISPEC
!
	ED_TOT=0.0D0
	DO ISPEC=1,NUM_SPECIES
	  IF(SPECIES_PRES(ISPEC))THEN
	    ED_TOT(1:ND)=ED_TOT(1:ND)+AT_NO(ISPEC)*POP_SPECIES(1:ND,ISPEC)
	  END IF
	END DO
	END SUBROUTINE
