        SUBROUTINE WRITE_ARRAY_ISO(A,ND,N,B,FILENAME1)
        IMPLICIT NONE
!      
        INTEGER :: ND
        INTEGER :: N
        INTEGER :: I,J,K
	INTEGER :: INDX
	INTEGER :: V
        REAL*8 :: A(ND,N)
        REAL*8 :: B(N)
        CHARACTER(LEN=40) :: FILENAME1
        CHARACTER(LEN=40) :: FILENAME2
        CHARACTER(LEN=15) :: STRING
!
        DO I=1,ND!,5
	  FILENAME2=FILENAME1
          FILENAME2=ADJUSTL(FILENAME2)
          J=INDEX(FILENAME2,' ')
          WRITE(STRING,'(I3.3)')I
          FILENAME2(J:J+2)=STRING(1:3)
          FILENAME2(J+3:)='.dat'
          OPEN(UNIT=7,FILE=FILENAME2,STATUS='UNKNOWN',ACTION='WRITE')
	  DO K=1,N
            WRITE(7,'(ES18.8,ES18.8)')B(K)*4.135668D-18,A(I,K)
          END DO
          CLOSE(UNIT=7)
        END DO
	RETURN
        END SUBROUTINE WRITE_ARRAY_ISO
