	MODULE MOD_RD_GAMRAY_CNTRL_VARIABLES
	IMPLICIT NONE
!
	REAL*8 :: V_GAUSS
	REAL*8 :: V_INF
	REAL*8 :: V_LINE
	REAL*8 :: V_TAIL
	REAL*8 :: V_BETWEEN
	REAL*8 :: BLUE_GAUSS
	REAL*8 :: RED_GAUSS
	REAL*8 :: COMP_TAIL_SPLIT_FRAC
!
	INTEGER :: NU_GRID_MAX
	INTEGER :: CHEB_ORDER
	INTEGER :: ANG_MULT
	INTEGER :: GAM_IT
	INTEGER :: GRAY_LINE_MIN
	INTEGER :: GRAY_TAIL_MIN1
	INTEGER :: GRAY_TAIL_MIN2
	INTEGER :: GRAY_TAIL_MIN3
	INTEGER :: GRAY_TAIL_MIN4
!
	LOGICAL :: NORM_GAM_LINES
	LOGICAL :: GRID_MIN_PTS
!
	END MODULE MOD_RD_GAMRAY_CNTRL_VARIABLES
