	MODULE MOD_RD_GAMRAY_CNTRL_VARIABLES
	IMPLICIT NONE
!
	REAL*8 :: V_GAUSS
	REAL*8 :: V_INF
	REAL*8 :: V_LINE
	REAL*8 :: V_TAIL
	REAL*8 :: V_BETWEEN
	REAL*8 :: V_END
	REAL*8 :: BLUE_GAUSS
	REAL*8 :: RED_GAUSS
	REAL*8 :: COMP_TAIL_SPLIT_FRAC
	REAL*8 :: EGAM_MIN
	REAL*8 :: EGAM_MAX
!
	INTEGER :: NU_GRID_MAX
	INTEGER :: CHEB_ORDER
	INTEGER :: ANG_MULT
	INTEGER :: GAM_IT
	INTEGER :: GRAY_LINE_MIN
	INTEGER :: GRAY_TAIL_MIN1
	INTEGER :: GRAY_TAIL_MIN2
	INTEGER :: GRAY_TAIL_MIN3
	INTEGER :: GRAY_TAIL_MIN4
	INTEGER :: GRAY_END_MIN
!
	CHARACTER(LEN=10) :: GAM_IB_METH
!
	LOGICAL :: NORM_GAM_LINES
	LOGICAL :: NORM_LINES_ONLY
	LOGICAL :: GRID_TST
	LOGICAL :: GRID_MIN_PTS
	LOGICAL :: OBS_REL_FULL
	LOGICAL :: DO_NORM_ETA
!
	END MODULE MOD_RD_GAMRAY_CNTRL_VARIABLES
